name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5 # or alternative dependency management
      - name: config key
        run: |
          cp .env.example .env
          php artisan cache:clear
          php artisan config:clear
          php artisan key:generate
      - uses: php-actions/phpunit@v3
    # ... then your own project steps ...
